# Generated by Django 3.2.3 on 2021-06-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210602_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
